### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Harrisanj** [ajseward/TradeSkillMaster#20]
Addon: TradeSkillMaster_AuctionDB
Message:  ...SkillMaster_AuctionDB\TradeSkillMaster_AuctionDB.lua:293: bad argument #2 to 'format' (number expected, got nil)
Date: 04/02/22 23:21:59
Client: 3.3.5
Locale: ruRU
Stack:
[C]: <pcall>
[string "*:OnLoad"]:4: <[string "*:OnLoad"]:1>
[C]: <format>
TSM_AuctionDB.lua:293: <TradeSkillMaster_AuctionDB.lua:230>
TSM\Core\Tooltips.lua:55: <Tooltips.lua:45>
TSM\Core\Tooltips.lua:72: <callback>
TSM\Libs\LibExtraTip\LibExtraTip.lua:114: <LibExtraTip.lua:98>
TSM\Libs\LibExtraTip\LibExtraTip.lua:160: <h>
Interface\AddOns\QuestHelper\manager_event.lua:22: <manager_event.lua:21>
Interface\AddOns\QuestHelper\manager_event.lua:43: <manager_event.lua:25>
Interface\AddOns\QuestHelper\manager_event.lua:163: <manager_event.lua:163>
...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:279: <LibExtraTip.lua:273>
TSM\Libs\LibExtraTip\LibExtraTip.lua:387: <LibExtraTip.lua:381>
[C]: <SetMerchantItem>
Interface\FrameXML\MerchantFrame.lua:439: <MerchantItemButton_OnEnter>
[string "*:OnEnter"]:1: <[string "*:OnEnter"]:1>
TSM Stack:
TSM_AuctionDB:GetTooltip("item:23638:0:0:0:0:0:0", 1)
Local Variables:

TSM Event Log:

Addons:
    AckisRecipeList (v2.0)
    ACP (3.3.4)
    AdiBags (v1.1-beta-7)
    AlixtraGiveMoney (1.0.0)
    Alt-Tab_Toggle (2.1.4beta)
    AtlasLoot (v5.11.03)
    Auc-Advanced (5.8.4723 (CreepyKangaroo))
    Auctionator (2.6.3)
    AutoScreenshot ()
    BeanCounter (5.8.4723 (CreepyKangaroo))
    BonusScanner (5.3)
    Capping (3.3.004)
    ChatBar (3.0)
    ClassLoot (r114)
    CorShootBar ()
    CorTotemBar ()
    Corvus (1.2-$Rev: 90 $)
    CorvusSpam (1.0)
    Cromulent (v1.5)
    FB_Broker (1.5a (FB 0.9.8d))
    Details_3DModelsPaths (r267)
    Details ()
    Details_DeathGraphs ()
    Details_EncounterDetails ()
    Details_DataStorage ()
    Details_SunderCount ()
    Details_TimeLine ()
    Details_TinyThreat ()
    Details_ChartViewer ()
    ElitistGroup (v1.7.6)
    Enchantrix (5.8.4723 (CreepyKangaroo))
    Enchantrix-Barker (5.8.4723 (CreepyKangaroo))
    EveryQuest_World_Events (r162)
    FemaleAnnouncer (v1.0.1-release)
    FindGroup (2.1)
    FishingBuddy (0.9.8p1)
    FB_OutfitDisplayFrame (0.9.8k)
    FB_TrackingFrame (0.9.8k)
    FB_InfoBar (0.9.8d)
    FB_MergeDatabase (0.9.8d)
    FuBar_FishingBuddyFu (2.2h)
    Gatherer (3.1.14)
    Gatherer_HUD (3.1.14)
    GathererDB_Wowhead (1.0.2009-12-09)
    GearScore (3.1.17 - Release)
    GTFO (2.5.3)
    GuildRecruiter (3.0)
    GuildCheck (v2.24)
    HandyNotes (v1.1.5)
    Icicle (0.9)
    Informant (5.8.4723 (CreepyKangaroo))
    InspectEquip (1.7.7)
    LilSparkysWorkshop (r90release)
    Mapster (1.3.9)
    MikScrollingBattleText (5.4.78)
    MSBTOptions ()
    NeedyGreedy (1.5.3)
    OpenAll (r44)
    Overachiever (v0.56)
    PallyPower (v3.2.10-release)
    QuestHelper (1.4.1)
    RaidRoll ()
    RaidRoll_EPGP ()
    RaidRoll_LootTracker ()
    SavedInstances (v3.0.1)
    Scrap ()
    Scrap_Merchant ()
    Scrap_Options ()
    SharedMedia (r178)
    Skillet (r167)
    SoundAlerter (1.0)
    Stubby (5.8.4723 (CreepyKangaroo))
    !Swatter (5.8.4723 (CreepyKangaroo))
    TidyPlates (5.13.3 (R39))
    TipTac (10.05.01)
    FB_Titan (0.9.8d)
    VuhDo (2.22)
    VuhDoOptions (2.22)
    WeakAuras (3.2.3)
    WeakAurasArchive ()
    WeakAurasModelPaths (2.16.0-beta1)
    WeakAurasOptions (3.2.3)
    WIM (3.3.7)
    TSM (v2.8.3)
    TSM_Accounting (v2.3)
    TSM_AuctionDB (v2.3.10)
    TSM_Auctioning (v2.3.3)
    TSM_Destroying (v2.1.1)
    TSM_ItemTracker (v2.0.8)
    TSM_Shopping (v2.3.6)
    TSM_Warehousing (v2.0.10)
    ElvUI_OptionsUI (1.06)
    ElvUI (6.08)
    DBM-Core ()
![image](https://user-images.githubusercontent.com/55931677/161399902-ea5b9bd1-2e89-4e0e-88b5-85edc13b3818.png)

**Comment by ajseward** [comment]
Please follow the instructions in the [https://github.com/ajseward/TradeSkillMaster/blob/master/README.md](Readme) to remove a previous install. 

Feel free to reopen if you still have issues
