### ISSUE TITLE
TSM error window every 2 seconds when crafting

### ISSUE THREAD

**Issue by WwariosS** [ajseward/TradeSkillMaster#22]
Addon: TradeSkillMaster_Crafting
Message:  ...ns\TradeSkillMaster_Crafting\Modules\CraftingGUI.lua:655: attempt to concatenate a nil value
Date: 04/16/22 05:55:52
Client: 3.3.5
Locale: enUS
Stack:
[C]: <pcall>
[string "*:OnLoad"]:4: <[string "*:OnLoad"]:1>
TSM_Crafting\Modules\CraftingGUI.lua:655: <handler>
TSM\GUI\ScrollingTable.lua:92: <ScrollingTable.lua:84>
TSM Stack:

Local Variables:

TSM Event Log:
1 | AUCTIONING:POST:STOPPED | nil
2 | AUCTIONING:SCANDONE | table: 346BFA88
3 | AUCTIONING:POST:START | table: 38E9D210
Addons:
    AckisRecipeList (v2.01-14-gfc58e9f)
    ACP (3.3.5)
    AdiBags (v1.1-beta-7)
    Auc-Advanced (5.8.4723 (CreepyKangaroo))
    Bartender4 (4.4.2-12-g94f3b58)
    BeanCounter (5.8.4723 (CreepyKangaroo))
    Cheese (1.0)
    Enchantrix (5.8.4723 (CreepyKangaroo))
    Enchantrix-Barker (5.8.4723 (CreepyKangaroo))
    GatherMate (v.1.25)
    GearScoreLite (3x04)
    Informant (5.8.4723 (CreepyKangaroo))
    Omen (v3.0.9)
    OmniCC (3.0.4)
    OmniCC_Config ()
    Postal (v3.4.0)
    ShadowedUF_Options (v3.2.12)
    ShadowedUnitFrames (v3.2.12)
    Skada (r300)
    SlideBar (5.8.4723 (CreepyKangaroo))
    Stubby (5.8.4723 (CreepyKangaroo))
    !Swatter (5.8.4723 (CreepyKangaroo))
    Warmane_AH-fix (1.5)
    WeakAuras (2.0.8)
    WeakAurasModelPaths (2.0.8)
    WeakAurasOptions (2.0.8)
    TSM (v2.8.3)
    TSM_Accounting (v2.3)
    TSM_AuctionDB (v2.3.10)
    TSM_Auctioning (v2.3.3)
    TSM_Crafting (v2.5.2)
    TSM_Destroying (v2.1.1)
    TSM_ItemTracker (v2.0.8)
    TSM_Shopping (v2.3.6)
    TSM_Warehousing (v2.0.10)
    DBM-Core ()

**Comment by vilzu** [comment]
Bump on this one. Used diff version be4 myself, deleted all older files be4 installing.
I am using auctioneer for pricing. I have ran into 2 problems, dunno relation. 

1) My Crafting module is literally blank. I'd like to enter it to set manual material prices for certain items.
2) Errors while opening crafting window. From what i grasped from the error code, seems like it is an issue where TSM tries to get crafting/material value from AUC and fails up.

Addon: TradeSkillMaster_Crafting
Message:  ...ns\TradeSkillMaster_Crafting\Modules\CraftingGUI.lua:230: attempt to index field 'content' (a nil value)
Date: 06/02/22 12:16:35
Client: 3.3.5
Locale: enUS
Stack:
[C]: <pcall>
[string "*:OnLoad"]:4: <[string "*:OnLoad"]:1>
TSM_Crafting\Modules\CraftingGUI.lua:230: <CraftingGUI.lua:218>
...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: <CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: <[string "safecall Dispatcher[1]"]:4>
[string "safecall Dispatcher[1]"]:13: <?>
...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: <Fire>
...Ons\DBM-Core\Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: <AceEvent-3.0.lua:119>
[C]: <TradeSkillOnlyShowMakeable>
[C]: <RunScript>
Interface\FrameXML\ChatFrame.lua:1996: <value>
Interface\FrameXML\ChatFrame.lua:4070: <ChatEdit_ParseText>
Interface\FrameXML\ChatFrame.lua:3660: <ChatEdit_SendText>
Interface\FrameXML\ChatFrame.lua:2477: <ChatFrame.lua:2470>
[C]: <UseAction>
Interface\FrameXML\SecureTemplates.lua:310: <handler>
Interface\FrameXML\SecureTemplates.lua:529: <SecureTemplates.lua:478>
TSM Stack:
TSM_Crafting.CraftingGUI:EventHandler("TRADE_SKILL_UPDATE")
TSMAPI:GetItemValue("item:39340:0:0:0:0:0:0", "AucMinBuyout")
TSM_Crafting:GetCustomPrice("min(aucminbuyout,vendorbuy)", "item:39340:0:0:0:0:0:0")
TSM_Crafting.Cost:GetMatCost("item:39340:0:0:0:0:0:0")
TSM_Crafting.Cost:GetCraftCost(57709)
TSM_Crafting.Cost:GetLowestCraftPrices("item:43120:0:0:0:0:0:0")
TSM_Crafting:GetCraftingCost("[Celestial Ink]", nil)
TSMAPI:GetItemValue("item:43120:0:0:0:0:0:0", "Crafting")
TSM_Crafting:GetCustomPrice("Crafting", "item:43120:0:0:0:0:0:0")
TSM_Crafting.Queue:HasLoop("item:43120:0:0:0:0:0:0", 0, table:1232658816)
Local Variables:

TSM Event Log:

Addons:
    _NPCScan (3.3.5.5)
    ACP (3.3.0)
    Atlas (1.17.0)
    Atlas_DungeonLocs (1.17.0)
    AtlasLoot (v5.11.04)
    Auc-Advanced (5.8.4723 (CreepyKangaroo))
    AutoFlood ()
    Bagnon (2.13.3)
    Bartender4 (4.4.2-12-g94f3b58)
    BasicMinimap (v1.72)
    BeanCounter (5.8.4723 (CreepyKangaroo))
    BonusScanner (5.3)
    ButtonFacade (3.3.333)
    BuyEmAll (2.9.2)
    ClassTimer (2.3.30300.4)
    Cromulent (v1.5.2)
    Enchantrix (5.8.4723 (CreepyKangaroo))
    EventAlert (4.2.26)
    GearScore (3.1.15 - Release)
    Grid (r1318)
    Informant (5.8.4723 (CreepyKangaroo))
    LootHog (3.3.3)
    MikScrollingBattleText (5.4.78)
    MoveAnything (3.3-09)
    MrPlow (v10.2.6.5-Beta)
    MSBTOptions ()
    MySales (1.2.0)
    NiceDamage (20400)
    Omen (v3.0.9)
    OmniCC (3.0)
    OmniCC_Config ()
    oUF (1.3.25)
    oUF_Nivaya ()
    oUF_Nivaya_Config ()
    Postal (r302)
    Quartz (3.0.3.1)
    RaidCooldowns (v3.3.5)
    SatrinaBuffFrame (3.1)
    SBFOptions (3.1)
    SellOMatic (v1.2.8a)
    Skada (r301)
    SnowfallKeyPress ()
    SpellID (1.01)
    Stubby (5.8.4723 (CreepyKangaroo))
    !Swatter (5.8.4723 (CreepyKangaroo))
    Talented (v2.4.6c-release)
    Talented_GlyphFrame (v2.4.6c-release)
    Talented_SpecTabs (v2.4.6c-release)
    TellMeWhen (1.2.5)
    TidyPlates (5.13.3 (R39))
    TitanAmmo (4.3.8.30300)
    Warmane_AH-fix (1.3)
    WIM (3.3.7)
    XLoot1.0 (1.1)
    TSM (v2.8.3)
    TSM_Accounting (v2.3)
    TSM_AuctionDB (v2.3.10)
    TSM_Auctioning (v2.3.3)
    TSM_Crafting (v2.5.2)
    TSM_Destroying (v2.1.1)
    TSM_ItemTracker (v2.0.8)
    TSM_Shopping (v2.3.6)
    TSM_Warehousing (v2.0.10)
    DBM-Core (7.11)

**Comment by ajseward** [comment]
@WwariosS You need to delete saved data from a previous install of TSM. Instructions are in the readme.

@vilzu Please try disabling other addons and see if that resolves it. Something is breaking one of the frame templates used by TSM.

**Comment by vilzu** [comment]
Done, did full clear for both tsm and auctioneer. All files for addon, and all account / char specific data files. No help. Didn't have this issue with previous version I used.  Also, this version worked for a file be4 bugging itself out.

Yhteistyöterveisin,
Ville Pakonen
VIOS Oy
Puh. +358417021110
________________________________
